aws_region = "aws_region_placeholder"
access_key = "access_key_placeholder"
secret_key = "secret_key_placeholder"
env        = "env_placeholder"
image_uri = "image_uri_placeholder"
client_id     = "client_id_placeholder"
client_secret = "client_secret_placeholder"